image: gitpod/workspace-base

tasks:
- name: install mamba, get data
  init: |
    wget "https://github.com/conda-forge/miniforge/releases/download/24.3.0-0/Mambaforge-24.3.0-0-Linux-x86_64.sh"
    bash Mambaforge-24.3.0-0-Linux-x86_64.sh -b -p /workspace/mambaforge && rm Mambaforge-24.3.0-0-Linux-x86_64.sh

    /workspace/conda/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba create -n annotation -c bioconda star scallop salmon samtools -y

    gzip -dr /workspace/ensembl-annotation/Annotating_the_genome/Fastq

  command: |
    /workspace/conda/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba activate annotation

    cd /workspace
    clear

vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

